// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5PfH_fBAMbKZ7B9ZgkFQiU7054mdkemE',
    appId: '1:1096235070543:web:276592541193a1ee1ae63a',
    messagingSenderId: '1096235070543',
    projectId: 'budget-4747f',
    authDomain: 'budget-4747f.firebaseapp.com',
    storageBucket: 'budget-4747f.appspot.com',
    measurementId: 'G-XF76H07D2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZgJenIL8j8o9IlqSF1SwCb8AiTgJNw4',
    appId: '1:1096235070543:android:e4fbdb34fe28cfec1ae63a',
    messagingSenderId: '1096235070543',
    projectId: 'budget-4747f',
    storageBucket: 'budget-4747f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbdjsY2dBX7OpPt5Y_ZKy12YPaHLp_Oo',
    appId: '1:1096235070543:ios:968c8239293811021ae63a',
    messagingSenderId: '1096235070543',
    projectId: 'budget-4747f',
    storageBucket: 'budget-4747f.appspot.com',
    iosBundleId: 'com.example.budget',
  );
}
